import {
  buildImportHeader,
  collectRootGraphCode,
  executeDirtyNodes,
  getCurrentBackendFile,
  getExecutableNodes,
  safeIdentifier,
  syncBackendOutput,
} from "../shared/backendGraphAssembler.js";
import { isBackendRouteNode } from "../shared/subgraphCollector.js";

function appendServiceReturn(code, node) {
  const resultSlot = node?.findOutputSlot?.("result");
  const resultVar =
    node?._lastResultVar ||
    (resultSlot == null || resultSlot < 0 ? "" : node.outputs?.[resultSlot]?._data);
  if (!resultVar) return code;
  return `${code}\nconst result = ${resultVar}\nreturn result`;
}

function buildRouteCode(routeLines, importStr) {
  if (!routeLines.length) return "";
  return `${buildImportHeader(importStr)}// Auto-generated by VueStudio
export default async function routes(fastify, options) {
  ${routeLines.join("\n\n  ")}
}
`;
}

function buildServiceCode(serviceEntries, importStr = "") {
  if (!serviceEntries.length) return "";
  const serviceLines = serviceEntries.map(([node, code]) => {
    const funcName = safeIdentifier(
      node.properties?.remark || node.title || `func_${String(node.id).slice(0, 8)}`,
      "serviceFunction",
    );
    const params = (node.properties?.passIn || [])
      .map((p) => safeIdentifier(p.name, "param"))
      .join(", ");
    return `export async function ${funcName}(${params}) {\n${appendServiceReturn(code, node)}\n}`;
  });
  return `${buildImportHeader(importStr)}// Auto-generated by VueStudio\n\n${serviceLines.join("\n\n")}`;
}

export default {
  type: "js",
  hasDragEditor: false,

  afterStep() {
    const graph = window._graph;
    const file = getCurrentBackendFile();
    const nodeId = file?.id;
    if (!graph || !nodeId) {
      return { jsCode: "", backendCode: "", backendServiceCode: "" };
    }

    const nodes = getExecutableNodes(graph);
    executeDirtyNodes(nodes, "backendService");
    const { routeCodeMap, serviceCodeMap, backendNodes, bgImportStr } =
      collectRootGraphCode(graph, nodes, {
        preferBackend: true,
        includeRoutes: true,
        includeServices: true,
        includePlainJs: false,
      });

    const routeLines = [];
    const serviceEntries = [];
    for (const node of backendNodes) {
      if (isBackendRouteNode(node)) {
        const code = routeCodeMap.get(node.id);
        if (code) routeLines.push(code);
      } else {
        const code = serviceCodeMap.get(node.id);
        if (code) serviceEntries.push([node, code]);
      }
    }

    const routeCode = buildRouteCode(routeLines, bgImportStr);
    const serviceCode = buildServiceCode(serviceEntries, bgImportStr);

    syncBackendOutput(nodeId, "", routeCode, serviceCode);
    return { jsCode: serviceCode || routeCode, backendCode: routeCode, backendServiceCode: serviceCode };
  },

  generateJS() {
    const result = this.afterStep();
    return result.backendServiceCode || result.backendCode || "";
  },
};
