import {
  buildImportHeader,
  collectRootGraphCode,
  executeDirtyNodes,
  getCurrentBackendFile,
  getExecutableNodes,
  safeIdentifier,
  syncBackendOutput,
} from "../shared/backendGraphAssembler.js";

function buildFunctionCode(file, bodyCode, importStr = "") {
  const config = file?.config || {};
  const functionName = safeIdentifier(
    config.functionName || file?.name,
    "backendFunction",
  );
  const params = Array.isArray(config.params)
    ? config.params
        .map((param) => safeIdentifier(param?.name, "param"))
        .filter(Boolean)
        .join(", ")
    : "";
  const body = bodyCode?.trim() ? bodyCode.trim() : "return undefined;";

  return `${buildImportHeader(importStr)}// Auto-generated by VueStudio

export async function ${functionName}(${params}) {
${body
  .split("\n")
  .map((line) => `  ${line}`)
  .join("\n")}
}
`;
}

export default {
  type: "js",
  hasDragEditor: false,

  afterStep() {
    const graph = window._graph;
    const file = getCurrentBackendFile();
    const nodeId = file?.id;
    if (!graph || !nodeId) {
      return { jsCode: "", backendCode: "", backendServiceCode: "" };
    }

    const nodes = getExecutableNodes(graph);
    executeDirtyNodes(nodes, "backendFunction");
    const { bodyCode, bgImportStr } = collectRootGraphCode(graph, nodes, {
      preferBackend: true,
      includeRoutes: false,
      includeServices: false,
      includePlainJs: true,
    });
    const serviceCode = buildFunctionCode(file, bodyCode, bgImportStr);

    syncBackendOutput(nodeId, "", "", serviceCode);
    return { jsCode: serviceCode, backendCode: "", backendServiceCode: serviceCode };
  },

  generateJS() {
    return this.afterStep().backendServiceCode || "";
  },
};
