/**
 * 后端代码生成策略
 *
 * 功能：
 * - 从 projectData.backendConfig 读取 HTTP API 和功能函数配置
 * - 生成 Fastify 路由文件
 * - 生成服务函数文件
 * - 支持图形编排（LiteGraph）和代码编排两种模式
 */

import { useProjectStore } from "src/stores/projectMange.js";

// ==================== 代码模板 ====================

/**
 * 生成 Fastify 路由文件模板
 */
const routeFileTemplate = (routeName, imports, routes) => `
// ==============================================
// Auto-generated by VueStudio
// Route: ${routeName}
// Generated at: ${new Date().toISOString()}
// ==============================================

${imports}

export default async function ${routeName}Routes(fastify, options) {
${routes}
}
`.trim();

/**
 * 生成服务函数文件模板
 */
const serviceFileTemplate = (serviceName, imports, functions) => `
// ==============================================
// Auto-generated by VueStudio
// Service: ${serviceName}
// Generated at: ${new Date().toISOString()}
// ==============================================

${imports}

${functions}
`.trim();

// ==================== 代码生成 ====================

/**
 * 生成单个 API 的路由代码
 */
function generateApiRoute(api) {
  const method = (api.method || "GET").toLowerCase();
  const path = api.path || "/api/endpoint";

  // 构建参数解构
  const paramExtractors = [];
  if (api.params && api.params.length > 0) {
    const queryParams = api.params.filter((p) => p.in === "query");
    const bodyParams = api.params.filter((p) => p.in === "body");
    const pathParams = api.params.filter((p) => p.in === "params");

    if (queryParams.length > 0) {
      paramExtractors.push(
        `const { ${queryParams.map((p) => p.name).join(", ")} } = request.query;`
      );
    }
    if (bodyParams.length > 0) {
      paramExtractors.push(
        `const { ${bodyParams.map((p) => p.name).join(", ")} } = request.body || {};`
      );
    }
    if (pathParams.length > 0) {
      paramExtractors.push(
        `const { ${pathParams.map((p) => p.name).join(", ")} } = request.params;`
      );
    }
  }

  // 构建路由选项
  const routeOptions = [];
  if (api.authRequired) {
    routeOptions.push("preHandler: fastify.authenticate");
  }

  const optionsStr =
    routeOptions.length > 0 ? `, { ${routeOptions.join(", ")} }` : "";

  // 获取逻辑代码
  const logicCode = api.logicType === "code" ? api.code || "// TODO: Implement logic" : "// Graph-based logic placeholder";

  // 格式化代码
  const formattedLogic = logicCode
    .split("\n")
    .map((line) => "    " + line)
    .join("\n");

  const paramExtractorStr =
    paramExtractors.length > 0
      ? paramExtractors.map((line) => "    " + line).join("\n") + "\n\n"
      : "";

  return `
  // ${api.name || "API"}: ${api.description || ""}
  fastify.${method}('${path}'${optionsStr}, async (request, reply) => {
${paramExtractorStr}${formattedLogic}
  });
`.trimEnd();
}

/**
 * 生成单个功能函数的代码
 */
function generateFunction(func) {
  const exportStr = func.exported !== false ? "export " : "";
  const asyncStr = func.isAsync !== false ? "async " : "";
  const funcName = func.name || "myFunction";

  // 构建参数列表
  const params = (func.params || [])
    .map((p) => {
      let paramStr = p.name || "arg";
      if (p.defaultValue) {
        paramStr += ` = ${p.defaultValue}`;
      }
      return paramStr;
    })
    .join(", ");

  // 获取逻辑代码
  const logicCode = func.logicType === "code" ? func.code || "// TODO: Implement logic" : "// Graph-based logic placeholder";

  // 格式化代码
  const formattedLogic = logicCode
    .split("\n")
    .map((line) => "  " + line)
    .join("\n");

  return `
/**
 * ${func.displayName || func.name}
 * ${func.description || ""}
 */
${exportStr}${asyncStr}function ${funcName}(${params}) {
${formattedLogic}
}
`.trim();
}

/**
 * 收集导入语句
 */
function collectImports(apis, functions) {
  const imports = new Set();

  // 常用的 Fastify 导入
  // imports.add("import { FastifyInstance } from 'fastify';");

  // 根据 API 配置添加导入
  for (const api of apis) {
    if (api.authRequired) {
      // 可能需要认证相关导入
    }

    // 如果引用了功能函数
    if (api.importedFunctions && api.importedFunctions.length > 0) {
      const funcNames = api.importedFunctions
        .map((funcId) => {
          const func = functions.find((f) => f.id === funcId);
          return func?.name;
        })
        .filter(Boolean);

      if (funcNames.length > 0) {
        imports.add(`import { ${funcNames.join(", ")} } from '../services/userFunctions.js';`);
      }
    }
  }

  return Array.from(imports).join("\n");
}

// ==================== 主策略类 ====================

export class BackendCodeStrategy {
  constructor(projectId) {
    this.projectId = projectId;
    this._projectStore = useProjectStore();
  }

  /**
   * 获取项目的后端配置
   */
  getBackendConfig() {
    const projectData = this._projectStore.getProjectData(this.projectId);
    if (!projectData) return null;
    return projectData.backend || {};
  }

  /**
   * 生成所有路由文件
   * @returns {Object} { fileName: fileContent }
   */
  generateRouteFiles() {
    const config = this.getBackendConfig();
    if (!config || !config.httpApis) return {};

    const apis = Object.values(config.httpApis);
    const functions = Object.values(config.functions || {});

    if (apis.length === 0) return {};

    // 按照路径前缀分组 API
    const groupedApis = this.groupApisByPath(apis);
    const files = {};

    for (const [prefix, groupApis] of Object.entries(groupedApis)) {
      const safeName = prefix.replace(/[^a-zA-Z0-9]/g, "") || "api";
      const fileName = `${safeName}.js`;

      const imports = collectImports(groupApis, functions);
      const routes = groupApis.map((api) => generateApiRoute(api)).join("\n");

      files[fileName] = routeFileTemplate(safeName, imports, routes);
    }

    return files;
  }

  /**
   * 生成服务函数文件
   * @returns {Object} { fileName: fileContent }
   */
  generateServiceFiles() {
    const config = this.getBackendConfig();
    if (!config || !config.functions) return {};

    const functions = Object.values(config.functions);

    if (functions.length === 0) return {};

    // 生成单个服务文件包含所有函数
    const imports = "";
    const funcsCode = functions.map((func) => generateFunction(func)).join("\n\n");

    return {
      "userFunctions.js": serviceFileTemplate("UserFunctions", imports, funcsCode),
    };
  }

  /**
   * 按路径前缀分组 API
   */
  groupApisByPath(apis) {
    const groups = {};

    for (const api of apis) {
      const path = api.path || "/api/default";
      // 提取第一级路径作为分组键
      const match = path.match(/^\/api\/([^/]+)/);
      const prefix = match ? match[1] : "default";

      if (!groups[prefix]) {
        groups[prefix] = [];
      }
      groups[prefix].push(api);
    }

    return groups;
  }

  /**
   * 生成完整的后端代码
   * @returns {Object} { routes: {}, services: {} }
   */
  generateAll() {
    return {
      routes: this.generateRouteFiles(),
      services: this.generateServiceFiles(),
    };
  }

  /**
   * 生成路由注册表
   * 用于自动注册所有用户路由
   */
  generateRouteRegistry() {
    const config = this.getBackendConfig();
    if (!config || !config.httpApis) return "";

    const apis = Object.values(config.httpApis);
    const groupedApis = this.groupApisByPath(apis);
    const prefixes = Object.keys(groupedApis);

    if (prefixes.length === 0) return "";

    const imports = prefixes
      .map((p) => `import ${p}Routes from './${p}.js';`)
      .join("\n");

    const registers = prefixes
      .map((p) => `  await fastify.register(${p}Routes);`)
      .join("\n");

    return `
// ==============================================
// Auto-generated by VueStudio
// Route Registry
// Generated at: ${new Date().toISOString()}
// ==============================================

${imports}

export async function registerUserRoutes(fastify) {
${registers}
}
`.trim();
  }
}

// ==================== 工厂函数 ====================

/**
 * 创建后端代码策略实例
 */
export function createBackendStrategy(projectId) {
  return new BackendCodeStrategy(projectId);
}

export default BackendCodeStrategy;
